name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install mermaid
        run: npm install mermaid mermaid.cli
      
      - name: Update mermaid.cli
        run: cp node_modules/mermaid/dist/mermaid.min.js node_modules/mermaid.cli/
      
      - name: Render diagram
        run: for f in *.mmd; do node_modules/.bin/mmdc -i $f -o $(echo "$f" | cut -f 1 -d '.').svg; done
           
      - name: Update repo
        run: |
          git config --global user.email 'ci@render.diagrams'; \
          git config --global user.name 'Render diagrams'; \
          git add .; git commit -m '...'; \
          git push origin ${GITHUB_REF##*/}
      
