name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test if
        if: "!contains(github.event.head_commit.message, '[skip package mod]')"
        run: echo "got here"

      - name: Do something else
        run: echo "something else"
